version: "3.9"

services:
  chroma_wo_auth:
    image: "chromadb/chroma:1.0.8"
    ports:
      - "8000:8000"

  chroma_w_auth:
    image: "chromadb/chroma:1.0.8"
    ports:
      - "8001:8000"
    environment:
      CHROMA_SERVER_AUTHN_CREDENTIALS: "test-token"
      CHROMA_SERVER_AUTHN_PROVIDER: "chromadb.auth.token_authn.TokenAuthenticationServerProvider"
      CHROMA_AUTH_TOKEN_TRANSPORT_HEADER: "Authorization"
