version: '3.9'

services:
  server:
    image: 'chromadb/chroma'
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-config chromadb/log_config.yml --timeout-keep-alive 30
    ports:
      - '8000:8000'
    volumes:
      - chroma-data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - CHROMA_SERVER_NOFILE=65535
      - ALLOW_RESET=true
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  chroma-data:
    driver: local